services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: snippetbox
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: mysql
      MYSQL_USER: mysql
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  db-test:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: snippetboxtest
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: test
      MYSQL_USER: test
    ports:
      - "3307:3306"
    volumes:
      - test:/var/lib/mysql

volumes:
  my-db:
  test: